#!/bin/bash
# scripts/annotation/setup.sh <domain>
#
# Provisions Argilla workspaces + users for one domain via pragmata's native
# `annotation setup`. The roster lives in configs/annotation/users.json (committed, no
# passwords); passwords are merged in at runtime from configs/annotation/users.secrets.json
# (gitignored, a {username: password} map). Any user without a password in the
# overlay gets one auto-generated by pragmata and printed once. Idempotent:
# existing users/workspaces are skipped.
#
# IMPORTANT: capture any "Generated passwords" printed on stdout - that's the
# only time they're shown.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
cd_root

[[ $# -eq 1 ]] || fatal "usage: $0 <domain>"
d="$1"
cfg="configs/annotation/domains/${d}.yaml"
roster="configs/annotation/users.json"
secrets="configs/annotation/users.secrets.json"
[[ -f "$cfg" ]]    || fatal "no config: $cfg"
[[ -f "$roster" ]] || fatal "no roster: $roster"

# Merge the gitignored password overlay into the committed roster.
users="/tmp/${d}_users.json"
if [[ -f "$secrets" ]]; then
  jq --slurpfile s "$secrets" \
    '$s[0] as $sec | map(if $sec[.username] then . + {password: $sec[.username]} else . end)' \
    "$roster" > "$users" || fatal "failed to merge $roster + $secrets"
else
  warn "no $secrets - pragmata will auto-generate all passwords"
  cp "$roster" "$users"
fi

"$PRAGMATA" annotation setup --users "$users" --config "$cfg"
